// constants for autocomplete  fields
export const JobTitleOptions = [
  "Software Engineer",
  "Data Scientist",
  "Data Science Intern",
  "Graduate Assistant",
  "Project Engineer",
  "Research Assistant",
  "Data Analyst",
  "Data Engineer",
  "Data Architect",
  "Data Analyst Intern",
  "Business Intelligence Analyst",
  "Embedded Systems Engineer",
  "DevOps Engineer",
  "Front-end Developer",
  "Back-end Developer",
  "Mobile Developer",
  "Full Stack Developer",
  "Machine Learning Engineer",
  "Data Visualization Engineer",
  "QA Engineer",
  "Cloud Engineer",
  "Data Science Engineer",
  "Data Science Manager",
  "Data Science Consultant",
  "Data Science Analyst",
  "Game Developer",
];

export const CourseTitleOptions = [
  "Big Data Analytics",
  "Computer Science",
  "Statistics",
  "Master of Science in Data Science",
  "Master of Science in Computational Science and Engineering",
  "Master of Science in Health Data Science",
  "Master of Science in Biostatistics",
  "Bachelor of Science in Computer Science and Engineering",
  "Master of Information and Data Science",
  "Mathematics",
  "Data Science",
  "Computer Engineering",
  "Computer Science and Engineering",
  "Mathematics with Computer Science",
  "Master of Engineering in Computer Science",
  "Master of Business Analytics",
  "Master of Science in Computer Science",
  "Master of Science in Computer Science and Information Systems",
  "Master of Science in Statistics and Data Science",
  "Electrical and Computer Engineering",
  "Biomedical Engineering",
  "Mechanical Engineering",
  "Master of Science in Statistical Science",
  "Master of Science in Applied Statistics",
];
export const SkillsOptions = [
  "Python",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Spark",
  "Hadoop",
  "Pyspark",
  "Apache Kafka",
  "Apache Airflow",
  "Apache Hive",
  "Apache Pig",
  "Apache Spark",
  "Apache Storm",
  "Apache Flink",
  "Apache HBase",
  "Apache Cassandra",
  "Apache Hadoop",
  "Apache HDFS",
  "Apache Zookeeper",
  "Apache Solr",
  "Java",
  "C++",
  "SQL",
  "R",
  "JavaScript",
  "Data Structures and algorithms",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Visualization",
  "Data Analysis",
  "Data Mining",
  "Data Engineering",
  "Data Architecture",
  "Data Modeling",
  "Data Warehousing",
  "Data Governance",
  "Data Quality",
  "Data Security",
  "Data Architecture",
  "NumPy",
  "Pandas",
  "Matplotlib",
  "Scikit-Learn",
  "Scala",
  "Tableau",
  "Power BI",
  "D3.js",
  "Plotly",
  "Seaborn",
  "Bokeh",
  "ggplot2",
  "Shiny",
  "Django",
  "Flask",
  "Spring",
  "Ruby on Rails",
  "Angular",
  "React",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "IBM Cloud",
  "Oracle Cloud",
  "SAP Cloud",
  "Salesforce",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Cassandra",
  "Redis",
  "Neo4j",
  "Elasticsearch",
  "HBase",
  "Hive",
  "CouchDB",
  "Couchbase",
  "RabbitMQ",
];
export const UniversityOptions = [
  "Harvard University",
  "Massachusetts Institute of Technology",
  "Stanford University",
  "California Institute of Technology",
  "University of Oxford",
  "University of Cambridge",
  "Swiss Federal Institute of Technology Zurich",
  "University of Chicago",
  "Imperial College London",
  "University of Pennsylvania",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of California",
  "University of Tokyo",
  "University of Toronto",
  "University of Waterloo",
  "National University of Singapore",
  "Peking University",
  "Tsinghua University",
  "University of Michigan",
  "Johns Hopkins University",
  "Cornell University",
  "University of Edinburgh",
  "University of Melbourne",
  "University of British Columbia",
  "National Taiwan University",
  "University of Hong Kong",
  "Seoul National University",
  "University of Sao Paulo",
];
export const GeographyOptions = [
  "United States",
  "Brazil",
  "South Korea",
  "Hong Kong",
  "Taiwan",
  "Australia",
  "United Kingdom",
  "Switzerland",
  "Singapore",
  "China",
  "Canada",
  "Japan",
  "India",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Mexico",
  "Russia",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Belgium",
  "Austria",
  "Poland",
  "Czech Republic",
  "Greece",
  "Portugal",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Slovakia",
  "Croatia",
  "Serbia",
  "Slovenia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Ukraine",
  "Belarus",
  "Moldova",
  "Turkey",
];

// Defaults

export const Defaults = {
  skills: ["SQL", "Python", "Power BI", "Apache Kafka", "TensorFlow"],
  salaryRange: "$50K - $100K",
  mentors: [
    {
      name: "Benjamin Rollins",
      linkedIn: "https://www.linkedin.com/in/benjamin-rollins-bbb2a872",
    },
    {
      name: "Hossein Zahed",
      linkedIn: "https://in.linkedin.com/in/data-scientist-6616b616b",
    },
    {
      name: "Victor Grazon",
      linkedIn: "https://ca.linkedin.com/in/data-scientist-9659071a7",
    },
    {
      name: "Lok Yi Lam",
      linkedIn: "https://ca.linkedin.com/in/data-scientist-2271391b8",
    },
    {
      name: "Brian Baller",
      linkedIn: "https://www.linkedin.com/in/brianballer",
    },
    {
      name: "Siddharth Kulkarni",
      linkedIn: "https://www.linkedin.com/in/siddharth-kulkarni-5b4b2b1b",
    },
  ],
  universities: [
    "University of California Berkeley",
    "Massachusetts Institute of Technology",
    "University of Toronto",
    "Carnegie Mellon University",
    "Georgia Institute of Technology",
    "University of California Los Angeles",
    "University of Washington",
    "University of Illinois at Urbana-Champaign",
    "University of Michigan",
    "University of California San Diego",
  ],
  employers: [
    "Google",
    "Microsoft",
    "Oracle",
    "IBM",
    "Intel",
    "Cisco",
    "Adobe",
    "Salesforce",
    "VMware",
  ],
};
